sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then exit 0; fi
- openssl aes-256-cbc -K $encrypted_4c19bef43f72_key -iv $encrypted_4c19bef43f72_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg --setdefaultusername
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg &&
  sfdx force:source:push -u ciorg && sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
- sfdx force:source:convert && sfdx force:mdapi:deploy -w 5 -u HubOrg -d metadataPackage*
